networks:
  app-network:
    driver: bridge

volumes:
  celery_data:

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env  # Updated path to the .env file
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    networks:
      - app-network
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A backend worker --loglevel=info
    env_file:
      - ./backend/.env  # Updated path to the .env file
    volumes:
      - ./backend:/app/backend
      - celery_data:/app/celery_data
    depends_on:
      - redis
      - backend
    networks:
      - app-network

  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A backend beat --loglevel=info
    env_file:
      - ./backend/.env  # Updated path to the .env file
    volumes:
      - ./backend:/app/backend
      - celery_data:/app/celery_data
    depends_on:
      - redis
      - backend
    networks:
      - app-network
  

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - app-network