# This docker file is used for production only.
#Not included db service, as we are using AWS RDS.

networks:
  app-network:
    driver: bridge

volumes:
  celery_data:
  backend:
  backend_static:
  daphne_socket:
  backend_media:

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.production
    environment:
      - SERVICE_TYPE=backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - backend:/app/backend
      - backend_static:/app/backend/staticfiles
      - backend_media:/app/backend/media
    networks:
      - app-network
    depends_on:
      redis:
        condition: service_healthy
    command:
      [
        "daphne",
        "-u",
        "/tmp/daphne/daphne.sock",
        "--bind",
        "0.0.0.0",
        "--port",
        "8000",
        "backend.asgi:application",
      ]
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile.production
    environment:
      - SERVICE_TYPE=celery
    env_file:
      - ./backend/.env
    volumes:
      - backend:/celery/backend
      - backend_static:/celery/staticfiles
      - backend_media:/celery/media
      - celery_data:/celery/celery_data
    depends_on:
      - redis
      - backend
    networks:
      - app-network

  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile.production
    environment:
      - SERVICE_TYPE=celery-beat
    env_file:
      - ./backend/.env
    volumes:
      - backend:/celery/backend
      - backend_static:/celery/staticfiles
      - backend_media:/celery/media
      - celery_data:/celery/celery_data
    depends_on:
      - redis
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - backend_static:/backend/staticfiles
      - backend_media:/backend/media
      - daphne_socket:/tmp/daphne # Daphne socket
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
