# Generated by Django 5.0.7 on 2024-08-20 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_courserequirement_title_lesson_video_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserequirement',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='courses.course'),
        ),
    ]
