# Generated by Django 5.0.7 on 2024-08-31 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_preview_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='currency',
        ),
    ]
