# Generated by Django 5.0.7 on 2024-08-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_mentorprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='experience',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
